### ISSUE TITLE
Andes Snackbar

### ISSUE THREAD

**Issue by jorGonzalez291292** [mercadolibre/fury_andesui-android#129]
Integrando el componente nos dimos cuenta que cuando el teclado esta levantado el [Snackbar](https://github.com/mercadolibre/fury_andesui-android/wiki/Andes-Snackbar) se muestra por detrás, en el bottom del parent y no en el top del teclado.

**Comment by jiurchuk** [comment]
Buenas!
¿Probaron con agregar `android:windowSoftInputMode="adjustResize"` en la declaración de la Activity que muestra el Snackbar en el Manifest?

**Comment by jorGonzalez291292** [comment]
Arreglado! Gracias!
